pipeline {
  agent any

  environment {
    IMAGE_NAME = "shishir78/quote-app:latest"
  }

  stages {
    stage('Clone') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('quote-app/devops-quote-hub') { // Path adjusted
          script {
            dockerImage = docker.build("${IMAGE_NAME}")
          }
        }
      }
    }

    stage('Push to DockerHub') {
      steps {
        withDockerRegistry([ credentialsId: 'dockerhub', url: '' ]) {
          script {
            dockerImage.push() // Push the image to DockerHub
          }
        }
      }
    }

    stage('Deploy') {
      steps {
        script {
          // Remove any existing container with the same name (if it exists)
          sh 'docker rm -f quote-app || true'

          // Pull the latest image from DockerHub
          sh "docker pull ${IMAGE_NAME}"

          // Run the Docker container with the correct ports
          sh "docker run -d --name quote-app -p 80:3000 ${IMAGE_NAME}"
        }
      }
    }
  }
}
